packages:
  - apps/*
  - packages/*

peerDependencyRules:
  allowedVersions:
    '@typescript-eslint/eslint-plugin>typescript': '6'
    '@typescript-eslint/parser>typescript': '6'
    '@typescript-eslint/project-service>typescript': '6'
    '@typescript-eslint/tsconfig-utils>typescript': '6'
    '@typescript-eslint/type-utils>typescript': '6'
    '@typescript-eslint/typescript-estree>typescript': '6'
    '@typescript-eslint/utils>typescript': '6'
