import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    pool: 'forks',
    fileParallelism: false,
    include: [
      'packages/**/src/**/*.test.ts',
      'packages/**/src/**/*.test.tsx',
      'apps/**/src/**/*.test.ts',
      'apps/**/src/**/*.test.tsx',
    ],
    coverage: {
      reportsDirectory: '.vitest-coverage',
      reporter: ['text', 'lcov'],
      exclude: [
        '**/dist/**',
        '**/*.d.ts',
        '.vitest-coverage/**',
        'coverage/**',
        'vitest.config.ts',
        'playwright.config.ts',
        'eslint.config.mjs',
        '**/vite.config.ts',
        'scripts/**',
        'test/e2e/**',
        'apps/cli/src/index.ts',
        'apps/daemon/src/index.ts',
        'apps/web-inspector/src/app.tsx',
        'apps/web-inspector/src/main.tsx',
        'apps/web-inspector/src/layout/**',
        'apps/web-inspector/src/components/card.tsx',
        'apps/web-inspector/src/components/empty-state.tsx',
        'apps/web-inspector/src/components/error-display.tsx',
        'apps/web-inspector/src/components/loading.tsx',
        'apps/web-inspector/src/components/page-header.tsx',
        'apps/web-inspector/src/views/dashboard.tsx',
        'apps/web-inspector/src/views/runs-list.tsx',
        'apps/web-inspector/src/views/receipts-list.tsx',
        'apps/web-inspector/src/views/receipt-detail.tsx',
        'apps/web-inspector/src/views/usage.tsx',
      ],
    },
  },
});
